### ISSUE TITLE
Summarising walking difficulties and building disaggregation by geography table

### ISSUE THREAD

**Issue by JosephCrispell** [Vanuatu-National-Statistics-Office/Population-Census-2020#25]
The walking difficulties table has the following format:
| province          | urban_rural | area_council          | sex                | walking                                                                                      | walkingDifficulties |
|-------------------|-------------|-----------------------|--------------------|----------------------------------------------------------------------------------------------|---------------------|
| ["province_name"] | [1\|2]      | ["area_council_name"] | ["Male"\|"Female"] | ["Cannot do at all"\|"Yes, lots of difficulty"\|"Yes, some difficulty"\|"No, no difficulty"] | [count]             |

And we would like to generate a table similar to the following:
![image](https://user-images.githubusercontent.com/17436210/136212447-13d7fbc9-4f24-44ff-9998-491d59675f14.png)

**Comment by JosephCrispell** [comment]
Hi @trara538,

I've completed a rough first pass at generating the summary table and formatting it in excel. The code is in the [`summarise_and_format_walking_difficulties.R`](https://github.com/Vanuatu-National-Statistics-Office/Population-Census-2020/blob/walking_difficulties_table/R/summarise_and_format_walking_difficulties.R) on the [`walking_difficulties_table`](https://github.com/Vanuatu-National-Statistics-Office/Population-Census-2020/tree/walking_difficulties_table) branch.

The `summarise_and_format_walking_difficulties.R` is written to run in the following data structure (Note only required files are shown):
```
Population-Census-2020/
              |-----data/
              |           \-----secure/
              |                         \-----walkDifficulties.csv
              \-----R/
                       \-----summarise_and_format_walking_difficulties.R
```
It will add a file called `walkDifficulties.xlsx` into the `data/secure/` folder, which contains the formatted excel table. Here's a screenshot of what it should look like (with values removed and only first few rows shown):
![image](https://user-images.githubusercontent.com/17436210/136465549-f2b7eea0-248e-43f0-8a5b-9b44999bdd6d.png)

I've tried to write the code in a way that means it can be readily applied to additional tables but there is likely to be more work required on this.

Give the code a go and let me know how you get on and whether it is going to be useful.

Thanks!

Joe

#### Tasks still remaining:
- [ ] Adding docstrings for functions
- [ ] Considering how code can be simplified
- [ ] Testing on a new table
